# 配置数据库连接信息
spring:
  datasource:
    username: root # 数据库用户名
    password: root # 数据库密码
    url: jdbc:mysql://192.168.56.10:3306/gulimall_ums?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai # 数据库连接URL
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动类名

  # 配置Nacos服务发现
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848 # Nacos服务器地址和端口
    # Sentinel配置
    sentinel:
      transport:
        # 配置Sentinel控制台地址
        dashboard: localhost:8080
        # Sentinel通信端口，默认8719端口，如果被占用会自动寻找未被占用的端口
        port: 8719

  # 应用名称配置
  application:
    name: gulimall-member

  redis:
    port: 6379
    host: 192.168.56.10

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss

  session:
    store-type: redis

# 配置Mybatis-plus
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml # 指定mapper文件位置
  global-config:
    db-config:
      id-type: auto # 主键生成策略

# 服务器端口配置
server:
  port: 8000

# 日志配置
logging:
  level:
    com.atguigu.gulimall.member: debug # 指定包的日志级别为debug

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'