# 服务器配置
server:
  port: 25000

# 应用配置
spring:
  application:
    name: gulimall-seckill # 应用名称

  # 服务发现配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos服务器地址

    # Sentinel配置
    sentinel:
      transport:
        # 配置Sentinel控制台地址
        dashboard: localhost:8080
        # Sentinel通信端口，默认8719端口，如果被占用会自动寻找未被占用的端口
        port: 8719

  # Redis配置
  redis:
    host: 192.168.56.10 # Redis服务器地址
    port: 6379 # Redis服务器端口

  # Session配置
  session:
    store-type: redis # 使用Redis存储Session

  #配置异步任务线程池
  task:
    execution:
      pool:
        core-size: 5
        max-size: 50

# 日志配置
logging:
  level:
    com.atguigu.gulimall.seckill: debug # 指定包的日志级别为debug

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'