# 服务器配置
server:
  port: 12000

# Spring应用配置
spring:
  # 应用基本信息
  application:
    name: gulimall-search
  # 云服务配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # Nacos服务发现地址
  # Redis配置
  redis:
    host: 192.168.56.10 # Redis服务器地址
    port: 6379 # Redis服务器端口

  # Thymeleaf模板引擎配置
  thymeleaf:
    cache: false # 关闭模板缓存

  # Session配置
  session:
    store-type: redis # 使用Redis存储Session

    # Sentinel配置
    sentinel:
      transport:
        # 配置Sentinel控制台地址
        dashboard: localhost:8080
        # Sentinel通信端口，默认8719端口，如果被占用会自动寻找未被占用的端口
        port: 8719

# 配置日志信息
logging:
  # 设置日志级别
  level:
    # 设置包com.atguigu.gulimall.search的日志级别为debug
    com.atguigu.gulimall.search: debug
    # 设置根日志级别的级别为warn
    root: warn

#开启feign对sentinel的支持
feign:
  sentinel:
    enabled: true

#暴露所有端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
